### ISSUE TITLE
Initial Spike

### ISSUE THREAD

**Issue by regcommunity-admin** [regcommunity/BIRDTables#2]
Exploritary work, to start forward engineering the BIRD LDM to a small set of tables.

**Comment by RBirdwatcher** [comment]
Initail spike suggests that we should use the version of the Ecore model which include Tables.

It also suggests that we should focus on one single 'hierarchy' in the LDM. and FRTB is a good candidate.

I also raises the question of whether it is good to keep the composite keys in the forward engineered input layer or replace them with sinlge more technical keys (unique_ids).
